# Generated by Django 4.2.21 on 2025-05-26 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_category_alter_product_image_subcategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_url',
            field=models.URLField(blank=True, max_length=1000, null=True, verbose_name='URL de imagen'),
        ),
    ]
