# Generated by Django 4.2.21 on 2025-05-26 23:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_product_code_alter_product_id'),
        ('shop', 'fix_cart_data_types'),
    ]

    operations = [
    ]
