# Generated by Django 4.2.21 on 2025-05-26 23:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0007_alter_product_options_cartitem_created_at_and_more'),
    ]

    operations = [
    ]
