# Generated by Django 4.2.21 on 2025-05-26 23:16

from django.db import migrations
from django.db import migrations

def fix_null_subcategories(apps, schema_editor):
    Product = apps.get_model('shop', 'Product')
    Subcategory = apps.get_model('shop', 'Subcategory')
    Category = apps.get_model('shop', 'Category')
    
    # Verificar si hay categorías
    if not Category.objects.exists():
        # Crear una categoría predeterminada
        default_category = Category.objects.create(name="General", slug="general")
    else:
        default_category = Category.objects.first()
    
    # Verificar si hay subcategorías
    if not Subcategory.objects.exists():
        # Crear una subcategoría predeterminada
        default_subcategory = Subcategory.objects.create(
            name="Sin categorizar",
            category=default_category
        )
    else:
        default_subcategory = Subcategory.objects.first()
    
    # Actualizar productos con subcategoría NULL
    Product.objects.filter(subcategory__isnull=True).update(subcategory=default_subcategory)

def reverse_func(apps, schema_editor):
    # No hacemos nada en la reversión
    pass

class Migration(migrations.Migration):
    # No modifiques las dependencias que Django generó automáticamente
    dependencies = [
        ('shop', '0008_fix_null_subcategories'),  # Este valor puede ser diferente en tu caso
    ]

    operations = [
        migrations.RunPython(fix_null_subcategories, reverse_func),
    ]

class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0008_fix_null_subcategories'),
    ]

    operations = [
    ]
