# Generated by Django 4.2.21 on 2025-05-26 23:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_fix_null_subcategories'),
    ]

    operations = [
    ]
