# Generated by Django 4.2.21 on 2025-05-26 23:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0010_fix_invalid_uuids'),
        ('shop', '0012_alter_product_options_alter_product_created_at_and_more'),
    ]

    operations = [
    ]
