# Generated by Django 4.2.21 on 2025-05-26 23:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0011_fix_invalid_cart_uuids'),
        ('shop', '0013_merge_20250526_1935'),
    ]

    operations = [
    ]
